### ISSUE TITLE
incompatibility with Blacklight >= 5.16.0

### ISSUE THREAD

**Issue by ebenenglish** [projectblacklight/blacklight-maps#81]
When attempting to use blacklight-maps v0.4.0 with blacklight >= 5.16.0, you get an error `uninitialized constant Blacklight::Configuration (NameError)` when starting your application.

Here's the full trace:
```
/home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps/engine.rb:9:in `<class:Engine>': uninitialized constant Blacklight::Configuration (NameError)
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps/engine.rb:7:in `<module:Maps>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps/engine.rb:6:in `<module:Blacklight>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps/engine.rb:5:in `<top (required)>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps.rb:7:in `require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps.rb:7:in `<module:Maps>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps.rb:4:in `<module:Blacklight>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/blacklight-maps-0.4.0/lib/blacklight/maps.rb:3:in `<top (required)>'
	from /home/username/boston-library/commonwealth-vlr-engine/lib/commonwealth-vlr-engine/engine.rb:4:in `require'
	from /home/username/boston-library/commonwealth-vlr-engine/lib/commonwealth-vlr-engine/engine.rb:4:in `<top (required)>'
	from /home/username/boston-library/commonwealth-vlr-engine/lib/commonwealth-vlr-engine.rb:1:in `require'
	from /home/username/boston-library/commonwealth-vlr-engine/lib/commonwealth-vlr-engine.rb:1:in `<top (required)>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /home/username/boston-library/Commonwealth-public-interface/config/application.rb:5:in `<top (required)>'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/username/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

`Blacklight::Maps::Engine` attempts to set some default configuration settings, which is what causes the error.

(In 5.16.0, the `Blacklight::Configuration` module was moved to `app/models/blacklight/configuration.rb`.)

There may be other issues related to using Blacklight >= 5.16.0, but this one is a major blocker to further work on bringing this project up to date with Blacklight 6.

@mejackreed @cbeer any ideas on where to move the default configuration stuff?

**Comment by cbeer** [comment]
Have you tried moving it into an initializer there?

**Comment by ebenenglish** [comment]
Can you point to an example? An initializer in `blacklight-maps/config/initializers`?

**Comment by cbeer** [comment]
Yep, exactly like that.

**Comment by starsplatter** [comment]
I updated one of my blacklights to 6 today and put in overrides for blacklight-maps helpers that were calling the old catalog paths, etc. Should I try forking and offering stuff back or is blacklight-maps for 6 already getting worked on somewhere?

**Comment by ebenenglish** [comment]
I've done some initial work on it through the process of updating my BL apps to 6. Was hoping to have 6-friendly release ready for sometime late next week (by 6/3 or so).

**Comment by ebenenglish** [comment]
PR for BL-6.*-friendly release submitted: https://github.com/projectblacklight/blacklight-maps/pull/82.
